// app/solutions/b2b/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { PageBanner } from "@/components/page-banner";
import { Button } from "@/components/ui/button";
import { 
  ArrowRight, 
  Building2,
  Boxes,
  Store,
  ClipboardCheck,
  CalendarClock,
  MessageSquareWarning,
  Settings2,
  LucideIcon
} from "lucide-react";

export const metadata: Metadata = {
  title: "B2B 零售分销 - Cube海外仓",
  description:
    "适用于整箱、整托、门店补货及批量订单配送场景，支持预约送货与签收回单管理。",
};

const features: { text: string; icon: LucideIcon }[] = [
  { text: "整箱、整托及批量订单出货", icon: Boxes },
  { text: "零售渠道分拨与门店补货", icon: Store },
  { text: "预约送货与签收回单管理", icon: ClipboardCheck },
  { text: "分阶段交付与项目型配送", icon: CalendarClock },
  { text: "异常反馈与交付协调服务", icon: MessageSquareWarning },
  { text: "定制化物流方案支持", icon: Settings2 },
];

export default function B2bPage() {
  return (
    <>
      <Navbar />
      <main>
        {/* Hero Banner */}
        <PageBanner
          tag="B2B 零售分销"
          title="批量配送与零售分拨"
          description="适用于整箱、整托、门店补货及批量订单配送场景，支持预约送货与签收回单管理，为零售渠道提供稳定可靠的分销物流支持。"
          image="/images/banner-b2b.jpg"
        />

        {/* Main Content Section */}
        <section className="py-16 lg:py-20">
          <div className="mx-auto max-w-7xl px-4 lg:px-8">
            <div className="flex flex-col lg:flex-row lg:items-center lg:gap-16">
              {/* Left - Image */}
              <div className="lg:w-1/2">
                <div className="rounded-2xl overflow-hidden shadow-xl border border-gray-100">
                  <Image
                    src="/images/banner-b2b.jpg"
                    alt="B2B 零售分销 - 批量配送作业"
                    width={700}
                    height={500}
                    className="w-full h-auto object-cover"
                  />
                </div>
              </div>
              {/* Right - Text content */}
              <div className="mt-8 lg:mt-0 lg:w-1/2">
                <h2 className="text-2xl lg:text-3xl font-bold text-foreground mb-4">
                  专业的 B2B 物流解决方案
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-8">
                  Cube海外仓为品牌商、经销商和零售企业提供专业的 B2B 物流服务。从批量出货到门店配送，我们提供完整的分销物流支持，确保货物准时、准确送达。
                </p>
                <ul className="space-y-3">
                  {features.map((item) => (
                    <li 
                      key={item.text} 
                      className="group flex items-center gap-4 p-3 rounded-xl cursor-pointer transition-all duration-300 hover:bg-primary/5 hover:shadow-md hover:translate-x-2"
                    >
                      <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 shrink-0 transition-all duration-300 group-hover:bg-primary group-hover:scale-110">
                        <item.icon className="h-5 w-5 text-primary transition-colors duration-300 group-hover:text-white" />
                      </div>
                      <span className="text-foreground font-medium transition-colors duration-300 group-hover:text-primary">{item.text}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="bg-white py-16 lg:py-20 border-t border-gray-100">
          <div className="mx-auto max-w-4xl px-4 lg:px-8 text-center">
            <Building2 className="mx-auto h-12 w-12 text-primary mb-6" />
            <h2 className="text-2xl lg:text-3xl font-bold text-foreground mb-4">
              开启您的 B2B 物流合作
            </h2>
            <p className="text-muted-foreground mb-8 max-w-2xl mx-auto">
              无论是零售门店补货、批发分销还是项目型配送，我们都能为您提供专业的 B2B 物流解决方案。
            </p>
            <div className="flex flex-wrap justify-center gap-4">
              <Button asChild size="lg" className="gap-2">
                <Link href="/contact">
                  立即咨询
                  <ArrowRight className="h-4 w-4" />
                </Link>
              </Button>
              <Button asChild variant="outline" size="lg">
                <Link href="/solutions">查看全部方案</Link>
              </Button>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}

// pages/solutions/b2b.vue
<template>
  <main>
    <PageBanner
      tag="B2B 零售分销"
      title="批量配送与门店补货"
      description="适用于整箱、整托、门店补货及批量订单配送场景，支持预约送货与签收回单管理。"
      image="/images/banner-b2b.jpg"
    />

    <section class="py-16 lg:py-20">
      <div class="mx-auto max-w-7xl px-4 lg:px-8">
        <div class="flex flex-col lg:flex-row lg:items-center lg:gap-16">
          <div class="lg:w-1/2">
            <div class="rounded-2xl overflow-hidden shadow-xl border border-gray-100">
              <img src="/images/service-b2b.jpg" alt="B2B 零售分销服务" class="w-full h-auto object-cover" />
            </div>
          </div>
          <div class="mt-8 lg:mt-0 lg:w-1/2">
            <h2 class="text-2xl lg:text-3xl font-bold text-gray-900 mb-4">
              专业 B2B 配送服务
            </h2>
            <p class="text-gray-500 leading-relaxed mb-8">
              为零售商、分销商和品牌提供英国本地 B2B 配送服务。支持整箱整托配送、门店定时补货、预约送货等多种模式，满足不同业务场景需求。
            </p>
            <ul class="space-y-3">
              <li v-for="item in features" :key="item.text" class="group flex items-center gap-4 p-3 rounded-xl transition-all duration-300 hover:bg-primary-500/5 hover:shadow-md hover:translate-x-2">
                <div class="flex h-10 w-10 items-center justify-center rounded-lg bg-primary-500/10 shrink-0 transition-all duration-300 group-hover:bg-primary-500 group-hover:scale-110">
                  <UIcon :name="item.icon" class="h-5 w-5 text-primary-500 transition-colors duration-300 group-hover:text-white" />
                </div>
                <span class="text-gray-900 font-medium transition-colors duration-300 group-hover:text-primary-500">{{ item.text }}</span>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>

    <section class="bg-white py-16 lg:py-20 border-t border-gray-100">
      <div class="mx-auto max-w-4xl px-4 lg:px-8 text-center">
        <UIcon name="i-lucide-building-2" class="mx-auto h-12 w-12 text-primary-500 mb-6" />
        <h2 class="text-2xl lg:text-3xl font-bold text-gray-900 mb-4">优化您的 B2B 供应链</h2>
        <p class="text-gray-500 mb-8 max-w-2xl mx-auto">
          无论是零售补货还是批量分销，我们都能提供高效可靠的配送支持。
        </p>
        <div class="flex flex-wrap justify-center gap-4">
          <UButton to="/contact" size="lg" class="gap-2">立即咨询 <UIcon name="i-lucide-arrow-right" class="h-4 w-4" /></UButton>
          <UButton to="/solutions" variant="outline" size="lg">查看全部方案</UButton>
        </div>
      </div>
    </section>
  </main>
</template>

<script setup lang="ts">
useSeoMeta({ title: 'B2B 零售分销 - Cube海外仓', description: '适用于整箱、整托、门店补货及批量订单配送场景。' })

const features = [
  { text: '整箱整托配送', icon: 'i-lucide-boxes' },
  { text: '门店定时补货', icon: 'i-lucide-store' },
  { text: '预约送货服务', icon: 'i-lucide-calendar' },
  { text: '签收回单管理', icon: 'i-lucide-file-check' },
  { text: '批量订单处理', icon: 'i-lucide-list-checks' },
  { text: '专业托盘配送', icon: 'i-lucide-truck' },
]
</script>
