// app/solutions/returns/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { PageBanner } from "@/components/page-banner";
import { Button } from "@/components/ui/button";
import { 
  ArrowRight, 
  RotateCcw,
  MapPin,
  PackageSearch,
  GitBranch,
  PackagePlus,
  RefreshCw,
  HeadphonesIcon,
  LucideIcon
} from "lucide-react";

export const metadata: Metadata = {
  title: "退货与售后支持 - Cube海外仓",
  description:
    "提供退件接收、检查、分类处理与后续履约支持，帮助客户优化退货流程。",
};

const features: { text: string; icon: LucideIcon }[] = [
  { text: "英国本地退件接收与登记", icon: MapPin },
  { text: "开箱检查与状态判断", icon: PackageSearch },
  { text: "分类处理与后续安排", icon: GitBranch },
  { text: "重新上架或退回支持", icon: PackagePlus },
  { text: "逆向履约与库存恢复", icon: RefreshCw },
  { text: "售后流程协同与异常处理", icon: HeadphonesIcon },
];

export default function ReturnsPage() {
  return (
    <>
      <Navbar />
      <main>
        {/* Hero Banner */}
        <PageBanner
          tag="退货与售后支持"
          title="高效处理退货，优化售后体验"
          description="提供退件接收、检查、分类处理与后续履约支持，帮助客户优化退货流程，降低退货处理成本，提升库存周转效率。"
          image="/images/banner-returns.jpg"
        />

        {/* Main Content Section */}
        <section className="py-16 lg:py-20">
          <div className="mx-auto max-w-7xl px-4 lg:px-8">
            <div className="flex flex-col lg:flex-row lg:items-center lg:gap-16">
              {/* Left - Image */}
              <div className="lg:w-1/2">
                <div className="rounded-2xl overflow-hidden shadow-xl border border-gray-100">
                  <Image
                    src="/images/service-returns.jpg"
                    alt="退货处理 - 检查与分类"
                    width={700}
                    height={500}
                    className="w-full h-auto object-cover"
                  />
                </div>
              </div>
              {/* Right - Text content */}
              <div className="mt-8 lg:mt-0 lg:w-1/2">
                <h2 className="text-2xl lg:text-3xl font-bold text-foreground mb-4">
                  完善的退货处理流程
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-8">
                  Cube海外仓提供专业的退货处理服务，从退件接收、开箱检查到分类处理，帮助卖家高效管理退货商品。通过规范化的处理流程，最大限度降低退货损失，提升库存价值回收率。
                </p>
                <ul className="space-y-3">
                  {features.map((item) => (
                    <li 
                      key={item.text} 
                      className="group flex items-center gap-4 p-3 rounded-xl cursor-pointer transition-all duration-300 hover:bg-primary/5 hover:shadow-md hover:translate-x-2"
                    >
                      <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 shrink-0 transition-all duration-300 group-hover:bg-primary group-hover:scale-110">
                        <item.icon className="h-5 w-5 text-primary transition-colors duration-300 group-hover:text-white" />
                      </div>
                      <span className="text-foreground font-medium transition-colors duration-300 group-hover:text-primary">{item.text}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="bg-white py-16 lg:py-20 border-t border-gray-100">
          <div className="mx-auto max-w-4xl px-4 lg:px-8 text-center">
            <RotateCcw className="mx-auto h-12 w-12 text-primary mb-6" />
            <h2 className="text-2xl lg:text-3xl font-bold text-foreground mb-4">
              优化您的退货处理流程
            </h2>
            <p className="text-muted-foreground mb-8 max-w-2xl mx-auto">
              无论是电商平台退货还是品牌售后，我们都能为您提供专业的退货处理与逆向物流支持。
            </p>
            <div className="flex flex-wrap justify-center gap-4">
              <Button asChild size="lg" className="gap-2">
                <Link href="/contact">
                  立即咨询
                  <ArrowRight className="h-4 w-4" />
                </Link>
              </Button>
              <Button asChild variant="outline" size="lg">
                <Link href="/solutions">查看全部方案</Link>
              </Button>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}

// pages/solutions/returns.vue
<template>
  <main>
    <PageBanner
      tag="退货与售后"
      title="高效退货处理支持"
      description="提供退件接收、检查、分类处理与后续履约支持，帮助客户优化退货流程。"
      image="/images/banner-returns.jpg"
    />

    <section class="py-16 lg:py-20">
      <div class="mx-auto max-w-7xl px-4 lg:px-8">
        <div class="flex flex-col lg:flex-row lg:items-center lg:gap-16">
          <div class="lg:w-1/2">
            <div class="rounded-2xl overflow-hidden shadow-xl border border-gray-100">
              <img src="/images/service-returns.jpg" alt="退货与售后服务" class="w-full h-auto object-cover" />
            </div>
          </div>
          <div class="mt-8 lg:mt-0 lg:w-1/2">
            <h2 class="text-2xl lg:text-3xl font-bold text-gray-900 mb-4">
              专业退货处理服务
            </h2>
            <p class="text-gray-500 leading-relaxed mb-8">
              为跨境卖家提供英国本地退货处理服务。从退件接收、质检分类到后续处理，帮助您降低退货损失，提升客户满意度。
            </p>
            <ul class="space-y-3">
              <li v-for="item in features" :key="item.text" class="group flex items-center gap-4 p-3 rounded-xl transition-all duration-300 hover:bg-primary-500/5 hover:shadow-md hover:translate-x-2">
                <div class="flex h-10 w-10 items-center justify-center rounded-lg bg-primary-500/10 shrink-0 transition-all duration-300 group-hover:bg-primary-500 group-hover:scale-110">
                  <UIcon :name="item.icon" class="h-5 w-5 text-primary-500 transition-colors duration-300 group-hover:text-white" />
                </div>
                <span class="text-gray-900 font-medium transition-colors duration-300 group-hover:text-primary-500">{{ item.text }}</span>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>

    <section class="bg-white py-16 lg:py-20 border-t border-gray-100">
      <div class="mx-auto max-w-4xl px-4 lg:px-8 text-center">
        <UIcon name="i-lucide-rotate-ccw" class="mx-auto h-12 w-12 text-primary-500 mb-6" />
        <h2 class="text-2xl lg:text-3xl font-bold text-gray-900 mb-4">优化您的退货流程</h2>
        <p class="text-gray-500 mb-8 max-w-2xl mx-auto">
          让退货不再成为负担，将退件转化为可再销售的库存资源。
        </p>
        <div class="flex flex-wrap justify-center gap-4">
          <UButton to="/contact" size="lg" class="gap-2">立即咨询 <UIcon name="i-lucide-arrow-right" class="h-4 w-4" /></UButton>
          <UButton to="/solutions" variant="outline" size="lg">查看全部方案</UButton>
        </div>
      </div>
    </section>
  </main>
</template>

<script setup lang="ts">
useSeoMeta({ title: '退货与售后支持 - Cube海外仓', description: '提供退件接收、检查、分类处理与后续履约支持。' })

const features = [
  { text: '退件接收与登记', icon: 'i-lucide-package-check' },
  { text: '外观与功能检测', icon: 'i-lucide-search' },
  { text: '分类分级处理', icon: 'i-lucide-layers' },
  { text: '重新包装上架', icon: 'i-lucide-package' },
  { text: '二次销售支持', icon: 'i-lucide-shopping-cart' },
  { text: '退货数据报告', icon: 'i-lucide-bar-chart-2' },
]
</script>
