// app/pages/technology.vue
<script setup lang="ts">
definePageMeta({
  layout: 'default'
})

useSeoMeta({
  title: '技术支持 - Cube海外仓',
  description: '先进的WMS仓储管理系统与自动化技术，实现库存、订单与物流可视化管理',
})

const features = [
  {
    icon: 'i-lucide-database',
    title: '库存管理',
    description: '实时库存监控、多仓库协同、库存预警与自动补货建议',
  },
  {
    icon: 'i-lucide-shopping-cart',
    title: '订单处理',
    description: '多平台订单同步、智能分拣调度、批量处理与优先级管理',
  },
  {
    icon: 'i-lucide-truck',
    title: '物流追踪',
    description: '全程物流可视化、多渠道配送管理、签收与异常处理',
  },
  {
    icon: 'i-lucide-bar-chart-3',
    title: '数据分析',
    description: '运营数据报表、库存周转分析、配送时效统计',
  },
  {
    icon: 'i-lucide-plug',
    title: 'API 对接',
    description: '支持主流电商平台、ERP/OMS 系统 API 标准对接',
  },
  {
    icon: 'i-lucide-shield-check',
    title: '安全保障',
    description: '数据加密存储、权限分级管理、操作日志审计',
  },
]
</script>

<template>
  <div class="pt-20">
    <PageBanner
      tag="TECHNOLOGY"
      title="技术支持"
      description="先进的WMS仓储管理系统与自动化技术，实现库存、订单与物流可视化管理"
      image="/images/banner-technology.jpg"
    />

    <section class="py-16 lg:py-24 bg-white">
      <div class="mx-auto max-w-7xl px-4 lg:px-8">
        <div class="text-center mb-12">
          <span class="inline-block px-4 py-1.5 rounded-full bg-orange-500/10 text-orange-500 text-sm font-medium mb-4">
            WMS 系统
          </span>
          <h2 class="text-2xl lg:text-3xl font-bold text-gray-900 mb-4">
            仓储管理系统功能
          </h2>
          <p class="text-gray-500 max-w-2xl mx-auto">
            自主研发的仓储管理系统，实现从入库、存储、分拣、出库到配送的全流程数字化管理
          </p>
        </div>

        <div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          <div 
            v-for="feature in features"
            :key="feature.title"
            class="group bg-white rounded-2xl p-8 shadow-md border border-gray-100 transition-all duration-300 hover:shadow-xl hover:-translate-y-1"
          >
            <div class="mb-5 flex h-14 w-14 items-center justify-center rounded-xl bg-orange-500/10 transition-all duration-300 group-hover:bg-orange-500 group-hover:scale-110">
              <UIcon :name="feature.icon" class="size-7 text-orange-500 transition-colors duration-300 group-hover:text-white" />
            </div>
            <h3 class="text-xl font-bold text-gray-900 mb-3">{{ feature.title }}</h3>
            <p class="text-gray-500">{{ feature.description }}</p>
          </div>
        </div>
      </div>
    </section>

    <!-- CTA -->
    <section class="py-16 lg:py-20 bg-[#f8fafc]">
      <div class="mx-auto max-w-4xl px-4 lg:px-8 text-center">
        <h2 class="mb-4 text-2xl font-bold text-gray-900 lg:text-3xl">
          想了解更多技术细节？
        </h2>
        <p class="mb-8 text-gray-500">
          我们的技术团队可以为您详细介绍系统功能与对接方案
        </p>
        <UButton to="/contact" size="lg" color="primary">
          联系技术支持
          <UIcon name="i-lucide-arrow-right" class="size-4 ml-2" />
        </UButton>
      </div>
    </section>
  </div>
</template>

// app/technology/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { PageBanner } from "@/components/page-banner";
import { Button } from "@/components/ui/button";

import { 
  ArrowRight,
  Database, 
  Package, 
  BarChart3, 
  Settings, 
  Monitor, 
  CheckCircle,
} from "lucide-react";

export const metadata: Metadata = {
  title: "技术支持 - Cube海外仓",
  description: "自研WMS仓储管理系统，支持多平台API对接，实现库存实时同步、订单自动处理、数据智能分析。",
};

const wmsFeatures = [
  { icon: Database, title: "实时库存管理", desc: "SKU级别库存追踪，多仓库同步更新，支持批次管理与效期预警" },
  { icon: Package, title: "智能订单处理", desc: "自动订单分配与波次拣货，支持多订单合并处理，提升拣货效率" },
  { icon: BarChart3, title: "数据分析报表", desc: "库存周转率、订单趋势、绩效报告等多维度数据分析" },
  { icon: Settings, title: "自动化工作流", desc: "入库质检、上架、出库全流程自动化，减少人工干预" },
  { icon: Monitor, title: "可视化看板", desc: "实时运营数据大屏展示，关键指标一目了然" },
];





export default function TechnologyPage() {
  return (
    <>
      <Navbar />
      <main>
        {/* Hero Banner */}
        <PageBanner
          tag="技术驱动"
          title="数字化仓储管理系统"
          description="自研WMS仓储管理系统，支持多平台API对接，实现库存实时同步、订单自动处理、数据智能分析，为您的仓储运营提供强大技术支撑。"
          image="/images/technology-wms.jpg"
        />

        {/* WMS Features Section */}
        <section className="py-16 lg:py-20 bg-white">
          <div className="mx-auto max-w-7xl px-4 lg:px-8">
            <div className="mb-10 text-center">
              <span className="inline-block px-4 py-1.5 rounded-full bg-primary/10 text-primary text-sm font-medium mb-4">核心系统</span>
              <h2 className="text-2xl lg:text-3xl font-bold text-foreground">WMS 仓储管理系统</h2>
            </div>
            <div className="flex flex-col lg:flex-row lg:items-center lg:gap-16">
              {/* Left - Image */}
              <div className="lg:w-1/2">
                <div className="rounded-2xl overflow-hidden shadow-xl border border-gray-100">
                  <Image
                    src="/images/technology-wms.jpg"
                    alt="WMS 仓储管理系统"
                    width={700}
                    height={500}
                    className="w-full h-auto object-cover"
                  />
                </div>
              </div>
              {/* Right - Content */}
              <div className="mt-8 lg:mt-0 lg:w-1/2">
                <p className="text-muted-foreground leading-relaxed mb-8">
                  自主研发的仓储管理系统，覆盖入库、存储、拣货、打包、发货全流程，支持多仓库、多货主管理，实现仓储作业的数字化与智能化。
                </p>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {wmsFeatures.map((item) => (
                    <div 
                      key={item.title} 
                      className="group flex items-start gap-3 p-3 rounded-xl cursor-pointer transition-all duration-300 hover:bg-primary/5 hover:shadow-md"
                    >
                      <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 shrink-0 transition-all duration-300 group-hover:bg-primary group-hover:scale-110">
                        <item.icon className="h-5 w-5 text-primary transition-colors duration-300 group-hover:text-white" />
                      </div>
                      <div>
                        <h3 className="font-semibold text-foreground text-sm transition-colors duration-300 group-hover:text-primary">{item.title}</h3>
                        <p className="text-xs text-muted-foreground mt-0.5">{item.desc}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Platform & API Integrations */}
        <section className="py-16 lg:py-20 bg-gradient-to-b from-muted/50 to-muted/20 border-t border-b border-gray-100">
          <div className="mx-auto max-w-7xl px-4 lg:px-8">
            <div className="text-center mb-12">
              <span className="inline-block px-4 py-1.5 rounded-full bg-primary/10 text-primary text-sm font-medium mb-4">开放集成</span>
              <h2 className="text-2xl lg:text-3xl font-bold text-foreground mb-4">
                全平台 API 无缝对接
              </h2>
              <p className="text-muted-foreground max-w-2xl mx-auto">
                提供标准化 RESTful API 接口，支持主流电商平台、快递服务商和 ERP 系统对接，实现订单自动同步、物流信息实时更新、库存数据多端一致。
              </p>
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="bg-gradient-to-b from-white to-gray-50 py-16 lg:py-20 border-t border-gray-100">
          <div className="mx-auto max-w-4xl px-4 lg:px-8 text-center">
            <CheckCircle className="mx-auto h-12 w-12 text-primary mb-6" />
            <h2 className="text-2xl lg:text-3xl font-bold text-foreground mb-4">
              体验数字化仓储管理
            </h2>
            <p className="text-muted-foreground mb-8 max-w-2xl mx-auto">
              预约系统演示，了解 Cube WMS 如何帮助您提升仓储运营效率、降��运营成本、优化库存管理。
            </p>
            <div className="flex flex-wrap justify-center gap-4">
              <Button asChild size="lg" className="gap-2 group transition-all duration-300 hover:scale-105 hover:shadow-lg">
                <Link href="/contact">
                  预约演示
                  <ArrowRight className="h-4 w-4 transition-transform duration-300 group-hover:translate-x-1" />
                </Link>
              </Button>
              <Button asChild variant="outline" size="lg" className="transition-all duration-300 hover:scale-105 hover:shadow-md">
                <Link href="/solutions">查看解决方案</Link>
              </Button>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
